"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CreditCard, ExternalLink, Megaphone, ShieldAlert, Swords, Users } from "lucide-react";

type Profile = { fullName: string; username: string; efootballIgn: string } | null;
type Payment = { id: string; amount: number; method: string; transactionId: string; senderNumber: string; screenshot: string | null; status: string; createdAt: string | Date } | null;
type Registration = { id: string; status: string; createdAt: string | Date; user: { email: string; profile: Profile }; payment: Payment };
type Group = { id: string; name: string; members: Array<{ participant: { user: { profile: Profile } } }> };
type Match = { id: string; groupId: string | null; roundName: string; matchNumber: number; status: string; player1Id: string | null; player1: { profile: Profile } | null; player2: { profile: Profile } | null; submissions: Array<{ submitterId: string; playerScore: number; opponentScore: number }> };
type Dispute = { id: string; status: string; reason: string; createdAt: string | Date; reporter: { profile: Profile }; reportedPlayer: { profile: Profile }; match: { roundName: string; matchNumber: number } };
type Tournament = { id: string; name: string; slug: string; description: string; status: string; totalSlots: number; minimumParticipants: number; groupCount: number; qualifiersPerGroup: number; entryFee: number; prizePool: number; registrationStart: string | Date; registrationEnd: string | Date; tournamentStart: string | Date; paymentInstructions: string | null; contactInfo: string | null; registrations: Registration[]; groups: Group[]; matches: Match[]; disputes: Dispute[]; announcements: Array<{ id: string; title: string; content: string; createdAt: string | Date }>; brackets: Array<{ id: string }> };
type Tab = "overview" | "registrations" | "participants" | "matches" | "groups" | "disputes" | "announcements" | "settings";
const tabs: Array<[Tab, string]> = [["overview", "Overview"], ["registrations", "Registrations"], ["participants", "Participants"], ["matches", "Matches"], ["groups", "Groups"], ["disputes", "Disputes"], ["announcements", "Announcements"], ["settings", "Settings"]];

function errorMessage(body: { error?: string | { message?: string } }) { return typeof body.error === "string" ? body.error : body.error?.message || "The action failed."; }
function name(profile: Profile) { return profile?.username || profile?.fullName || "Unknown player"; }

export function TournamentWorkspaceClient({ tournament }: { tournament: Tournament }) {
  const [tab, setTab] = useState<Tab>("overview"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [filter, setFilter] = useState("ALL");
  const [title, setTitle] = useState(""); const [content, setContent] = useState("");
  const [settingsData, setSettingsData] = useState({ name: tournament.name, description: tournament.description, totalSlots: tournament.totalSlots, entryFee: tournament.entryFee, prizePool: tournament.prizePool, paymentInstructions: tournament.paymentInstructions || "", contactInfo: tournament.contactInfo || "" });
  const approved = tournament.registrations.filter((item) => item.status === "APPROVED").length;
  const pendingPayments = tournament.registrations.filter((item) => item.payment && ["PENDING", "UNDER_REVIEW"].includes(item.payment.status));
  const openDisputes = tournament.disputes.filter((item) => ["OPEN", "UNDER_REVIEW"].includes(item.status));
  const filteredRegistrations = useMemo(() => tournament.registrations.filter((item) => filter === "ALL" || (filter === "PAYMENT_SUBMITTED" ? !!item.payment && ["PENDING", "UNDER_REVIEW"].includes(item.payment.status) : item.status === filter)), [filter, tournament.registrations]);

  async function action(path: string, method = "POST", payload?: unknown) { setBusy(true); setMessage(""); try { const response = await fetch(path, { method, headers: payload === undefined ? undefined : { "Content-Type": "application/json" }, body: payload === undefined ? undefined : JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(errorMessage(body)); setMessage(body.message || "Changes saved."); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "The action failed."); } finally { setBusy(false); } }
  async function rejectPayment(id: string) { const reason = window.prompt("Why is this payment being rejected?"); if (reason) await action(`/api/v1/admin/payments/${id}/reject`, "POST", { reason }); }
  async function publish(event: React.FormEvent) { event.preventDefault(); await action(`/api/v1/tournaments/${tournament.slug}/announcements`, "POST", { title, content }); }
  async function saveSettings(event: React.FormEvent) { event.preventDefault(); await action(`/api/v1/tournaments/${tournament.slug}`, "PUT", { ...settingsData, paymentInstructions: settingsData.paymentInstructions || null, contactInfo: settingsData.contactInfo || null }); }

  const progression = (() => {
    if (["DRAFT", "UPCOMING"].includes(tournament.status)) return { label: "Open registration", run: () => action(`/api/v1/tournaments/${tournament.slug}`, "PUT", { status: "REGISTRATION_OPEN" }) };
    if (tournament.status === "REGISTRATION_OPEN") return { label: "Close registration", run: () => action(`/api/v1/tournaments/${tournament.slug}`, "PUT", { status: "REGISTRATION_CLOSED" }) };
    if (tournament.status === "REGISTRATION_CLOSED" && tournament.groups.length === 0) return approved >= tournament.minimumParticipants ? { label: "Generate groups", run: () => action(`/api/v1/tournaments/${tournament.slug}/groups`, "POST", { groupCount: tournament.groupCount }) } : { reason: `Approve at least ${tournament.minimumParticipants} players before generating groups.` };
    const groupMatches = tournament.matches.filter((match) => match.groupId);
    if (["GROUP_STAGE", "ONGOING"].includes(tournament.status) && tournament.groups.length > 0 && groupMatches.length === 0) return { label: "Generate fixtures", run: () => action(`/api/v1/tournaments/${tournament.slug}/fixtures`) };
    if (["GROUP_STAGE", "ONGOING"].includes(tournament.status) && groupMatches.length > 0 && tournament.brackets.length === 0) return groupMatches.every((match) => match.status === "CONFIRMED") ? { label: "Generate knockout bracket", run: () => action(`/api/v1/tournaments/${tournament.slug}/bracket`, "POST", { topPerGroup: tournament.qualifiersPerGroup }) } : { reason: "Confirm every group result before generating the knockout bracket." };
    if (["KNOCKOUT_STAGE", "ONGOING"].includes(tournament.status) && tournament.brackets.length > 0) { const final = tournament.matches.find((match) => match.roundName === "Final"); return final?.status === "CONFIRMED" ? { label: "Complete tournament", run: () => window.confirm("Complete this tournament and publish its final results? This progression cannot be reversed.") && action(`/api/v1/tournaments/${tournament.slug}/complete`) } : { reason: "Confirm the final before completing the tournament." }; }
    return null;
  })();

  return <main className="page-container">
    <header className="page-hero"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-cyan-400"><ArrowLeft className="h-4 w-4" /> Dashboard</Link><Link href={`/tournaments/${tournament.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-300">Public page <ExternalLink className="h-4 w-4" /></Link></div><div className="mt-4"><span className="rounded-full bg-cyan-500/10 px-3 py-1 text-xs font-black text-cyan-300">{tournament.status.replaceAll("_", " ")}</span><h1 className="mt-3 break-words text-2xl font-black text-white sm:text-4xl">{tournament.name}</h1><p className="mt-2 text-sm text-slate-400">Tournament control room</p></div></header>
    <nav className="flex gap-2 overflow-x-auto pb-2" aria-label="Tournament management">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`min-h-10 shrink-0 rounded-xl px-4 text-xs font-black ${tab === key ? "bg-cyan-500 text-slate-950" : "border border-slate-700 text-slate-300"}`}>{label}</button>)}</nav>
    {message && <p role="status" className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-4 py-3 text-sm text-cyan-200">{message}</p>}

    {tab === "overview" && <section className="space-y-5"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={<Users />} label="Approved" value={`${approved}/${tournament.totalSlots}`} /><Metric icon={<CreditCard />} label="Payments to review" value={pendingPayments.length} /><Metric icon={<Swords />} label="Matches completed" value={`${tournament.matches.filter((match) => match.status === "CONFIRMED").length}/${tournament.matches.length}`} /><Metric icon={<ShieldAlert />} label="Open disputes" value={openDisputes.length} /></div><div className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-slate-500">Registration window</p><p className="mt-1 text-sm text-white">{new Date(tournament.registrationStart).toLocaleDateString()} – {new Date(tournament.registrationEnd).toLocaleDateString()}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Tournament start</p><p className="mt-1 text-sm text-white">{new Date(tournament.tournamentStart).toLocaleString()}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Current phase</p><p className="mt-1 text-sm text-white">{tournament.status.replaceAll("_", " ")}</p></div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-lg font-black text-white">Next tournament action</h2>{progression ? "label" in progression ? <button disabled={busy} onClick={progression.run} className="mt-4 min-h-11 rounded-xl bg-emerald-400 px-5 text-sm font-black text-slate-950 disabled:opacity-50">{busy ? "Working…" : progression.label}</button> : <p className="mt-3 text-sm text-amber-300">{progression.reason}</p> : <p className="mt-3 text-sm text-slate-400">No progression action is required right now.</p>}</div></section>}

    {tab === "registrations" && <section className="space-y-4"><div className="flex gap-2 overflow-x-auto">{["ALL", "PENDING_PAYMENT", "PAYMENT_SUBMITTED", "APPROVED", "REJECTED"].map((key) => <button key={key} onClick={() => setFilter(key)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${filter === key ? "bg-amber-400 text-slate-950" : "bg-slate-800 text-slate-300"}`}>{key.replaceAll("_", " ")}</button>)}</div>{filteredRegistrations.map((item) => <article key={item.id} className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 lg:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><p className="font-bold text-white">{name(item.user.profile)}</p><p className="break-all text-xs text-slate-400">{item.user.email} · {item.status.replaceAll("_", " ")}</p>{item.payment && <p className="mt-2 text-xs text-slate-300">{item.payment.method} · {item.payment.amount} · TrxID {item.payment.transactionId} · {item.payment.senderNumber}</p>}{item.payment?.screenshot && <a href={item.payment.screenshot} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-cyan-400">View payment evidence</a>}</div>{item.payment && ["PENDING", "UNDER_REVIEW"].includes(item.payment.status) && <div className="flex gap-2"><button disabled={busy} onClick={() => action(`/api/v1/admin/payments/${item.payment!.id}/approve`)} className="min-h-10 rounded-xl bg-emerald-400 px-4 text-xs font-black text-slate-950">Approve</button><button disabled={busy} onClick={() => rejectPayment(item.payment!.id)} className="min-h-10 rounded-xl border border-rose-500/50 px-4 text-xs font-black text-rose-300">Reject</button></div>}</article>)}{filteredRegistrations.length === 0 && <Empty>No registrations in this view.</Empty>}</section>}

    {tab === "participants" && <section className="space-y-3">{tournament.registrations.filter((item) => item.status === "APPROVED").map((item) => { const group = tournament.groups.find((candidate) => candidate.members.some((member) => member.participant.user.profile?.username === item.user.profile?.username)); const matches = tournament.matches.filter((match) => match.player1?.profile?.username === item.user.profile?.username || match.player2?.profile?.username === item.user.profile?.username); return <article key={item.id} className="grid gap-2 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="font-bold text-white">{name(item.user.profile)}</p><p className="text-xs text-slate-400">{item.user.profile?.efootballIgn || "IGN unavailable"}</p></div><p className="text-xs text-slate-300">{group?.name || "Not grouped"} · {matches.filter((match) => match.status === "CONFIRMED").length}/{matches.length} matches complete</p></article>; })}{approved === 0 && <Empty>No approved participants yet.</Empty>}</section>}

    {tab === "matches" && <section className="space-y-3">{tournament.matches.map((match) => { const submission = match.submissions[0]; const p1 = submission ? (submission.submitterId === match.player1Id ? submission.playerScore : submission.opponentScore) : null; const p2 = submission ? (submission.submitterId === match.player1Id ? submission.opponentScore : submission.playerScore) : null; return <article key={match.id} className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="text-xs font-bold text-cyan-400">{match.roundName} · Match {match.matchNumber}</p><p className="mt-1 font-bold text-white">{name(match.player1?.profile || null)} vs {name(match.player2?.profile || null)}</p><p className="text-xs text-slate-400">{match.status.replaceAll("_", " ")}{submission ? ` · Submitted ${p1}-${p2}` : ""}</p></div>{submission && ["RESULT_SUBMITTED", "UNDER_REVIEW", "DISPUTED"].includes(match.status) && <button disabled={busy} onClick={() => action(`/api/v1/matches/${match.id}/verify`, "POST", { player1Score: p1, player2Score: p2 })} className="min-h-10 rounded-xl bg-emerald-400 px-4 text-xs font-black text-slate-950">Verify result</button>}</article>; })}{tournament.matches.length === 0 && <Empty>Fixtures have not been generated.</Empty>}</section>}

    {tab === "groups" && <section className="space-y-4"><Link href={`/tournaments/${tournament.slug}`} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-700 px-4 text-xs font-bold text-cyan-300">View live standings and bracket <ExternalLink className="h-4 w-4" /></Link><div className="grid gap-4 md:grid-cols-2">{tournament.groups.map((group) => <article key={group.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h2 className="font-black text-white">{group.name}</h2><ol className="mt-3 space-y-2">{group.members.map((member, index) => <li key={`${group.id}-${index}`} className="rounded-lg bg-slate-950 px-3 py-2 text-sm text-slate-300">{index + 1}. {name(member.participant.user.profile)}</li>)}</ol></article>)}{tournament.groups.length === 0 && <Empty>Groups have not been generated.</Empty>}</div></section>}

    {tab === "disputes" && <section className="space-y-3"><Link href="/disputes" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-rose-500/15 px-4 text-sm font-black text-rose-300">Open moderation queue <ExternalLink className="h-4 w-4" /></Link>{tournament.disputes.map((item) => <article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs font-bold text-rose-300">{item.status.replaceAll("_", " ")} · {item.match.roundName} #{item.match.matchNumber}</p><p className="mt-2 font-bold text-white">{item.reason}</p><p className="text-xs text-slate-400">{name(item.reporter.profile)} reported {name(item.reportedPlayer.profile)}</p></article>)}{tournament.disputes.length === 0 && <Empty>No disputes for this tournament.</Empty>}</section>}

    {tab === "announcements" && <section className="grid gap-5 lg:grid-cols-2"><form onSubmit={publish} className="space-y-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="flex items-center gap-2 font-black text-white"><Megaphone className="h-5 w-5 text-amber-400" /> Publish update</h2><input required minLength={3} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Announcement title" className="min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 text-white" /><textarea required minLength={3} rows={6} value={content} onChange={(event) => setContent(event.target.value)} placeholder="What should participants know?" className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /><button disabled={busy} className="min-h-11 rounded-xl bg-amber-400 px-5 text-sm font-black text-slate-950">Publish</button></form><div className="space-y-3">{tournament.announcements.map((item) => <article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="font-bold text-white">{item.title}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{item.content}</p></article>)}{tournament.announcements.length === 0 && <Empty>No announcements yet.</Empty>}</div></section>}

    {tab === "settings" && <form onSubmit={saveSettings} className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 sm:grid-cols-2"><Input label="Tournament name" value={settingsData.name} onChange={(value) => setSettingsData({ ...settingsData, name: value })} /><Input label="Total slots" type="number" value={settingsData.totalSlots} onChange={(value) => setSettingsData({ ...settingsData, totalSlots: Number(value) })} /><Input label="Entry fee" type="number" value={settingsData.entryFee} onChange={(value) => setSettingsData({ ...settingsData, entryFee: Number(value) })} /><Input label="Prize pool" type="number" value={settingsData.prizePool} onChange={(value) => setSettingsData({ ...settingsData, prizePool: Number(value) })} /><label className="grid gap-2 text-sm font-bold text-slate-300 sm:col-span-2">Description<textarea rows={5} value={settingsData.description} onChange={(event) => setSettingsData({ ...settingsData, description: event.target.value })} className="rounded-xl border border-slate-700 bg-slate-950 p-3 font-normal text-white" /></label><label className="grid gap-2 text-sm font-bold text-slate-300 sm:col-span-2">Payment instructions<textarea rows={4} value={settingsData.paymentInstructions} onChange={(event) => setSettingsData({ ...settingsData, paymentInstructions: event.target.value })} className="rounded-xl border border-slate-700 bg-slate-950 p-3 font-normal text-white" /></label><Input label="Contact information" value={settingsData.contactInfo} onChange={(value) => setSettingsData({ ...settingsData, contactInfo: value })} /><button disabled={busy} className="min-h-11 self-end rounded-xl bg-cyan-500 px-5 text-sm font-black text-slate-950">Save tournament</button></form>}
  </main>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: React.ReactNode }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="h-5 w-5 text-cyan-400">{icon}</div><p className="mt-3 text-xl font-black text-white">{value}</p><p className="text-xs text-slate-400">{label}</p></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">{children}</div>; }
function Input({ label, value, onChange, type = "text" }: { label: string; value: string | number; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2 text-sm font-bold text-slate-300">{label}<input required type={type} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 font-normal text-white" /></label>; }
